---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Load used libraries
```{r message=FALSE}
library(dplyr)
library(ggplot2)
library(scales)
```

## Loading and preprocessing the data
```{r echo=TRUE}
df <- read.csv('activity.csv', as.is=TRUE)
df$date <- as.Date(df$date)
head(df)
str(df)
```

## What is mean total number of steps taken per day?
```{r echo=TRUE}
group_by(df, date) %>%
    summarize(total_steps = sum(steps)) %>%
    ggplot(aes(x=total_steps)) + 
    geom_bar(binwidth=1000) +
    scale_x_continuous(labels=comma, name='Total Steps') +
    scale_y_continuous(name='Days', breaks=c(0:10)) + 
    ggtitle('Frequency of Daily Total Steps')

# find the mean and median
group_by(df, date) %>%
    summarize(total_steps = sum(steps)) %>%
    summarize(mean_total_steps_per_day = mean(total_steps, na.rm=TRUE),
              median_total_steps_per_day = median(total_steps, na.rm=TRUE)) %>%
    knitr::kable()
```


## What is the average daily activity pattern?
```{r echo=TRUE}
group_by(df, interval) %>%
    summarize(avg_steps = mean(steps, na.rm=TRUE)) %>%
    ggplot(aes(x=interval, y=avg_steps)) +
    geom_line() + 
    ggtitle('Mean Steps Taken by Time Interval') +
    scale_y_continuous(name='Mean Number of Steps') +
    scale_x_continuous(name='Time Interval', labels=comma)

# Which 5-minute interval has the most steps on average?
group_by(df, interval) %>%
    summarize(avg_steps = mean(steps, na.rm=TRUE)) %>%
    filter(avg_steps == max(avg_steps)) %>%
    knitr::kable()
```


## Imputing missing values
```{r echo=TRUE}
# how many NAs are there?
# it seems only the 'steps' variable has NAs:
summary(df)
# so count of rows with NA is basically the number of NAs in the 'steps' column:
sum(is.na(df$steps))

# fill in NAs using the mean step count of the interval in question
df_imputed <- group_by(df, interval) %>%
    mutate(steps = ifelse(is.na(steps), mean(steps, na.rm=TRUE), steps)) %>%
    as.data.frame

# NAs are now gone:
summary(df_imputed)

# histogram of the data with imputed values
# now more days right at the mean/median bucket
group_by(df_imputed, date) %>%
    summarize(total_steps = sum(steps)) %>%
    ggplot(aes(x=total_steps)) + 
    geom_bar(binwidth=1000) +
    scale_x_continuous(labels=comma, name='Total Steps') +
    scale_y_continuous(name='Days', breaks=c(0:20)) + 
    ggtitle('Frequency of Daily Total Steps')

# have the mean and the median changed?
# almost not at all (the median increased by 1)
group_by(df_imputed, date) %>%
    summarize(total_steps = sum(steps)) %>%
    summarize(mean_total_steps_per_day = mean(total_steps, na.rm=TRUE),
              median_total_steps_per_day = median(total_steps, na.rm=TRUE)) %>%
    knitr::kable()
```


## Are there differences in activity patterns between weekdays and weekends?
```{r echo=TRUE}
# create factor variable for weekend vs. weekday 
df_imputed <- mutate(df_imputed,
       weekend = factor(ifelse(weekdays(date) %in% c('Sunday', 'Saturday'),
                               'Weekend', 'Weekday')))

# use facet grid to display the mean step trends by interval by weekend/weekday,
# it seems weekends have higher levels of activity across the entire day while
# weekdays have a spike in the morning followed by fewer steps until the evening.
# Also the subject wakes up later on the weekend and goes to bed later!:
group_by(df_imputed, weekend, interval) %>%
    summarize(avg_steps = mean(steps)) %>%
    ggplot(aes(x=interval, y=avg_steps)) +
    geom_line() +
    scale_y_continuous(name='Mean Number of Steps') +
    scale_x_continuous(name='Time Interval', labels=comma) +
    ggtitle('Mean Steps by Time Interval, Weekday vs. Weekend') + 
    facet_grid(weekend~.)
```
